name: Backup MySQL (Aiven SSL)

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Crear archivo CA
        run: echo "${{ secrets.DB_CA_CERT }}" > ca.pem

      - name: Crear backup
        run: |
          mysqldump \
            -h ${{ secrets.DB_HOST }} \
            -P ${{ secrets.DB_PORT }} \
            -u ${{ secrets.DB_USER }} \
            -p${{ secrets.DB_PASS }} \
            --ssl-ca=ca.pem \
            ${{ secrets.DB_NAME }} > backup.sql

      - name: Comprimir backup
        run: gzip backup.sql

      - name: Subir backup
        uses: actions/upload-artifact@v4
        with:
          name: backup-${{ github.run_id }}
          path: backup.sql.gz